# Template from https://github.com/fixposition/fixposition_driver/blob/main/fixposition_driver_ros2/launch/tcp.yaml
fixposition_driver:
  ros__parameters:
    fp_output:
      formats: [
                "ODOMETRY", "LLH", "ODOMENU", "ODOMSH", "RAWIMU", "CORRIMU", "GNSSANT", "GNSSCORR", "TEXT", "TF", # FP_A
                "GPGGA", "GPGLL", "GNGSA", "GPGST", "GPHDT", "GPRMC", "GPVTG", "GPZDA", "GXGSV" # NMEA
               ]
      type: "tcp"
      port: "21000"
      ip: "10.15.20.5" # change to VRTK2's IP address in the network
      rate: 200
      reconnect_delay: 5.0 # wait time in [s] until retry connection
      qos_type: "sensor_short" # Supported types: "sensor_short", "sensor_long", "default_short", "default_long"
    customer_input:
      speed_topic: "/fixposition/speed"
      rtcm_topic: "/fixposition/rtcm"