services:
  fixposition:
    image: husarion/fixposition:humble
    network_mode: host
    ipc: host
    volumes:
      - ./config/tcp.yaml:/ros2_ws/install/fixposition_driver_ros2/share/fixposition_driver_ros2/launch/tcp.yaml
    command: ros2 launch fixposition_driver_ros2 tcp.launch 
  
  odometry_converter:
    image: husarion/fixposition:humble
    network_mode: host
    ipc: host
    volumes:
      - ./config/odom_converter.yaml:/ros2_ws/install/fixposition_odometry_converter_ros2/share/fixposition_odometry_converter_ros2/launch/odom_converter.yaml
    command: ros2 launch fixposition_odometry_converter_ros2 odom_converter.launch

  foxglove:
    image: husarion/foxglove:humble
    volumes:
      - ./config/foxglove.json:/src/FoxgloveDefaultLayout.json
    environment:
      - FOXGLOVE_PORT=8080
      - ROSBRIDGE_PORT=9090
    ports:
      - 8080:8080

  rosbridge:
    image: husarion/rosbridge-server:humble
    network_mode: host
    ipc: host
    ports:
      - 9090:9090
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml